#ifndef OLED_AEGIS_VERSION_H
#define OLED_AEGIS_VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 2
#define APP_VERSION_PATCH 1
#define APP_VERSION_BUILD 0

#define APP_VERSION_STRING "1.2.1"
#define APP_VERSION_WIDE L"1.2.1"

#endif
